#node js image
FROM node:latest

#place to put all the source files
WORKDIR /usr/src/app

#copy all the files that react needs to run
COPY package.json .
COPY package-lock.json .
COPY . .

#install npm i guess
RUN npm install --silent

#the react app will be available on port 3000
EXPOSE 3000

ENTRYPOINT ["npm","start"]
