version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - server
    stdin_open: true
    networks:
      - app-network
  
  server:
    build:
      context: ./server
      dockerfile: dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
    volumes:
      - ./server/:/user/src/app
      - /usr/src/app/node_modules
    stdin_open: true
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
